name: waterStrip-project
services:
  postgres:
    image: postgres:16-alpine
    container_name: waterStrip-db
    ports:
      - "${POSTGRES_PORT_OUT}:5432"
    volumes:
      - waterStrip-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - waterStrip-net

  backend:
    build: ./backend
    container_name: waterStrip-backend
    ports:
      - ${BackendPORT}:3001
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - waterStrip-net
    env_file:
      - ./.env
    # command: >
    #   sh -c "
    #   npm run db:push &&
    #   npm run start
    #   "
  frontend:
    container_name: waterStrip-frontend
    build: ./frontend
    ports:
      - ${NGINX_PORT}:80
    networks:
      - waterStrip-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}

  ml-service:
    build: ./ml-service
    container_name: waterStrip-ml
    ports:
      - "5000:5000"
    networks:
      - waterStrip-net


volumes:
  waterStrip-data:

networks:
  waterStrip-net:
    driver: bridge
